services:
  api:
    build: .
    container_name: consolid-prod-api
    ports:
      - "8000:8000"
    environment:
      - DOCIQ_CORS_ORIGINS=["http://localhost:3000","http://localhost:3001","http://localhost:5173","http://127.0.0.1:3000","http://127.0.0.1:3001","http://127.0.0.1:5173"]
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" 